// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_FWv51HFIm-Elpt1Z4ZzfOonJP6YcNVI',
    appId: '1:223107202151:web:b9a3f4585f4b3911a568c2',
    messagingSenderId: '223107202151',
    projectId: 'gessportflutter',
    authDomain: 'gessportflutter.firebaseapp.com',
    storageBucket: 'gessportflutter.firebasestorage.app',
    measurementId: 'G-29V2TDMRL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGFz8ygrUD6EnsebCsXXKoLEk2UyTbB5M',
    appId: '1:223107202151:android:45d82829c459834ea568c2',
    messagingSenderId: '223107202151',
    projectId: 'gessportflutter',
    storageBucket: 'gessportflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJCapOg0MFpaXT_px9b1a3wMKu_w7O9zY',
    appId: '1:223107202151:ios:7520b0b10dd353cda568c2',
    messagingSenderId: '223107202151',
    projectId: 'gessportflutter',
    storageBucket: 'gessportflutter.firebasestorage.app',
    iosClientId: '223107202151-tej5n4rjb88519eeeusdm20bcvjcl97n.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluterMaricarmen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJCapOg0MFpaXT_px9b1a3wMKu_w7O9zY',
    appId: '1:223107202151:ios:7520b0b10dd353cda568c2',
    messagingSenderId: '223107202151',
    projectId: 'gessportflutter',
    storageBucket: 'gessportflutter.firebasestorage.app',
    iosClientId: '223107202151-tej5n4rjb88519eeeusdm20bcvjcl97n.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluterMaricarmen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_FWv51HFIm-Elpt1Z4ZzfOonJP6YcNVI',
    appId: '1:223107202151:web:16f79000c2241b0ba568c2',
    messagingSenderId: '223107202151',
    projectId: 'gessportflutter',
    authDomain: 'gessportflutter.firebaseapp.com',
    storageBucket: 'gessportflutter.firebasestorage.app',
    measurementId: 'G-X73WB5V9Z0',
  );
}
